on:
  push: #when pushed
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev
    
jobs:
  push-test: #test when pushed
    name: push Gradle build and test
    runs-on: ubuntu-latest #set OS
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Gradle Build Action #ref from marketplace -> gradle build action
      uses: gradle/gradle-build-action@v2.3.3
    - name: Gradle Test
      run: ./gradlew test
    
