on:
  push: #when pushed
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev
    
jobs:
  push-test: #test when pushed
    name: push Gradle build and test
    runs-on: ubuntu-18.04 #set OS
    steps:
    - name: Gradle Build Action #ref from marketplace -> gradle build action
      uses: gradle/gradle-build-action@v2.3.3
    - name: Gradle Test
      uses: ./gradlew test
    
